import ast
import json
import os

class SecurityScanner(ast.NodeVisitor):
    def __init__(self):
        self.found_flaws = 0

    def visit_Call(self, node):
        # Look for the dangerous 'eval' function
        if isinstance(node.func, ast.Name):
            if node.func.id == 'eval':
                print(f"    🚨 ALERT: Found insecure 'eval()' function on line {node.lineno}!")
                self.found_flaws += 1
        
        self.generic_visit(node)

def scan_dataset():
    file_path = "../../data/full_dataset.json"
    
    # Check if Team A has generated the file yet
    if not os.path.exists(file_path):
        print("Dataset not found! Run generate_data.py first.")
        return

    print("Opening the dataset and scanning for vulnerabilities...\n")
    
    # Open the JSON file generated by Team A
    with open(file_path, "r") as file:
        dataset = json.load(file)
        
    # Loop through every example in the dataset
    for index, entry in enumerate(dataset):
        print(f"Scanning Example {index + 1} ({entry['vulnerability_type']})...")
        
        bad_code = entry.get("bad_code", "")
        
        try:
            # Turn the AI-generated code into an AST and scan it
            tree = ast.parse(bad_code)
            scanner = SecurityScanner()
            scanner.visit(tree)
            
            if scanner.found_flaws == 0:
                print("    ✅ No obvious 'eval()' flaws found in this snippet.")
                
        except SyntaxError:
            print("    ❌ AI generated invalid Python syntax. Skipping.")
            
        print("-" * 40)

if __name__ == "__main__":
    scan_dataset()